os:
  - osx
language: swift
osx_image: xcode10.1
script:
  - xcodebuild -enableCodeCoverage YES -scheme WeakDictionary-iOS -project WeakDictionary.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.0' build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  - xcodebuild -scheme WeakDictionary-iOS -project WeakDictionary.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.0' build test
  - xcodebuild -scheme WeakDictionary-tvOS -project WeakDictionary.xcodeproj -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' build test
  - xcodebuild -scheme WeakDictionary-macOS -project WeakDictionary.xcodeproj build test
  - xcodebuild -scheme WeakDictionary-watchOS -project WeakDictionary.xcodeproj build
  - gem install cocoapods
  - pod repo update --silent
  - pod lib lint --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)